app <- ShinyDriver$new("../../", seed = 1)
app$snapshotInit("test_analysis")

app$setInputs(nav = "Design")
app$setInputs(analysis_design = "Observational")
app$setInputs(analysis_design_button_next = "click")
app$uploadFile(analysis_data_upload = "../../data/linear_data.csv")
app$snapshot()
app$setInputs(analysis_data_button_columnAssignSave = "click")
app$setInputs(analysis_data_save_groupings = "click")
app$setInputs(analysis_data_save = "click")
app$setInputs(analysis_plot_tabs = "Common Support Plots")
app$snapshot()
app$setInputs(analysis_plot_tabs = "Balance Plots")
app$setInputs(analysis_plots_balance_button_next = "click")
app$setInputs(analysis_model_estimand = "ATE")
app$setInputs(analysis_model_button_next = "click", timeout_ = 40000)
app$setInputs(interpretation = "Non-Causal")
app$snapshot()
