concepts_header <- navbarMenu(
  title = 'Learn',
  concepts_page,
  "-----",
  # tabPanel(title = "Test your understanding", 
  #          includeMarkdown(file.path("UI", "markdowns", 'concepts.md'))), 
  tabPanel(title = 'Causal estimands',
           ui_learning_estimands(id = module_ids$learning$estimands)),
  tabPanel(title = 'Post-treatment variables',
           ui_learning_post_treatment(id = module_ids$learning$post_treatment)),
  tabPanel(title = 'Potential outcomes', 
           ui_learning_potential_outcomes(id = module_ids$learning$potential_outcomes)),
  # tabPanel(title = 'Bias and efficiency',
  #          ui_learning_bias_efficiency(id = module_ids$learning$bias_efficiency)),
  # tabPanel(title = 'PotentialOutcomes',
  #          PotentialOutcomesUI(id = "concepts_potentialoutcomes")),
  tabPanel(title = 'Randomization', 
           ui_learning_randomization(id = module_ids$learning$randomization))
  # tabPanel(title = 'PO Test', 
  #          poUI(id = 'potential_outcomes_test')),
  # tabPanel(title = "Fundamental problem",
  #          includeMarkdown(file.path("UI", "markdowns", 'concepts.md'))),
  # tabPanel(title = "Regression methods",
  #          includeMarkdown(file.path("UI", "markdowns", 'concepts.md')))
  )
