---
title: "post treatment variables"
author: "George Perrett"
date: "2/1/2022"
output: pdf_document
---

# Post-treatment variables

## Do not adjust for post-treatment variables 

Including *post-treatment variables* in models for both randomized and observational studies generally is not a good idea and should be avoided. By *post-treatment variables*, we mean variables that can be effected by the treatment and our measured after treatment assignment. When post-treatment variables are included as a predictor or input in a causal analysis [estimates]() of the treatment effect can be [biased]()

### Consider a simple example 

A farmer wants to know if a non-toxic environmentally friendly pest-control method will cause plants to grow taller. The farmer conducted an experiment by randomly assigning half of their 400 plants to revive pest-control and the other half to receive no pest-control. Each plants treatment assignment was recorded with the variable `pest_control` . 

At the end of the growing season, 6 months later, the farmer measures the height of each plant with the variable `height` as well as whether or not there were any bug bites on each plant with the variable `bugs` (plant had no bugs = 0, plant had bugs = 1). The variable `bugs` is a post-treatment variable because it was measured after the treatment had been assigned and it is possible that values of `bugs` may be effected by receiving the pest-control treatment. 


The farmer is unsure if they should control for `bugs` when analyzing the results of the experiment. You can compare the results of an analyses that control for the post-treatment variable `bugs` or do not control for the post-treatment variable `bugs`.


### Interactive Plot goes here

Including post-treatment variables can drastically impact the results of experiments. The data for this example was simulated so we know that, on average, the pest-control caused plants to grow 1.52 inches taller than they would have grown without the pest-control. We can see that the analysis without the post-treatment variable `bugs` is very close to the true treatment effect. The analysis that includes the post-treatment variable `bugs` is far off from the true treatment effect and would lead an incorrect assessment of the non-toxic environmentally friendly pest-control!

# Why are analysis with post-treatment variables biased?

To demonstrate how adjusting for post-treatment variables introduces bias, consider another hypothetical example: does an exercise program increase muscle strength? The treatment variable `z` records whether or not an individual participated in the exercise program, the pre-treatment variable. Mid-way through the study, weekly trips to the gym was recorded for each individual with the post-treatment variable `gym`. 

Post-treatment variables, like `gym`, have different [potential outcomes]() that depend on the treatment variable. This is the primary problem of controlling for post-treatment variables. The table below shows the [potential outcomes]() and observed outcomes of `gym` for 2 individuals from our exercise study.In real contexts, we would not have access to both [potential outcomes]() but we can imagine them for the purposes of this example. Notice that two individuals differ in `z` but have the same value for `gym` despite haviving different [potential outcomes](). Controlling for `gym` is not a fair comparison of `strength` because we are not accounting for how `z` changes the value of `gym`. This is not a problem for pre-treatment varibales becuase thier value can not be changed or influenced by `z`. 



#### Text if do not contorl for bugs is selected

When `bugs` **is not included** in the analysis, the causal effect of `pest_control` is a comparison between the average height of plants that received the pest-control (colored in red) against the average height and plants that did not receive the pest-control(colored in blue). 

Plants that received the pest-control grew an average of **1.595 inches taller**, than they would have grown had they not received the pest-control. 

#### End of Text if do not contorl for bugs is selected

#### Text if contorl for bugs is selected

When `bugs` **is included** in the analysis, the causal effect of `pest_control` is a comparison between the average height of plants that received the pest-control (colored in red) against the average height and plants that did not receive the pest-control(colored in blue) **that is made within groups of plants that had bugs and did not have bugs**. 

Plants that received the pest-control grew an average of **-0.1778 inches taller**, than they would have grown had they not received the pest-control. 

#### End of Text if contorl for bugs is selected


Including post-treatment variables can drastically impact the results of both randomized experiments and observational studies. The data for this example was [simulated]() so we know that, on average, the pest-control caused plants to grow 1.52 inches taller than they would have grown without the pest-control. We can see that the analysis without the post-treatment variable `bugs` is very close to the true treatment effect. The analysis that includes the post-treatment variable `bugs` is far off from the true treatment effect and would lead an incorrect assessment of the non-toxic environmentally friendly pest-control!

Some fields would describe `bugs` as *mediator*, *process variable* or *intermediate outcome* meaning that the treatment appears to work by protecting pants from being eaten by bugs. *Mediator*, *process variable*, *intermediate outcome* are all post-treatment variables and should not be adjusted for.  

<br>

## Identifying post-treatment variables

Variables are coincided to be post-treatment if they can be influenced by the treatment variable. Consider another hypothetical example where you are tasked with evaluating if a high quality pre-school program causes higher reading levels among 2nd graders. Besides the treatment variable and outcome variable you collected several covariates. Before the pre-school program began you recorded parent(s) education and income. Long after the program ended you used administrative records to access childrens' birth weight, birth zip-code and childrens' reading level in 1st grade.

We can imagine data as existing on two timelines. The first timeline representing when variables were measured in relation to the treatment and the second representing when variables occurred relative to the treatment: 


#### tinelines are here

<br>

All variables measured before the treatment are automatically pre-treatment variables and should be included as covariates. Variables measured after the treatment have the possibility to be post-treatment variables but this is not necessarily the case. Despite being collected long after the treatment, the variables `birth weight` and `birth zip-code` are pre-treatment variables because their values were determined before the pre-school program began. It is impossible to imagine a world in which receiving the pre-school program could change a child's `birth weight`. Demographic and biologically fixed variables like age or sex can not reasonably be influenced by the treatment and should be included as covariates

Variables that have been measured after the treatment and can plausibly be influenced by the treatment are considered post-treatment variables. This is the case for `1st grade reading level` which was measured after the treatment and can realistically be influenced by whether or not a child received high quality pre-school. 

It may not always be clear when variables were measured. Accidentally including post-treatment variables in your analysis will likely [bias]() the [estimate of your treatment effect](). In situations where a variable could be influenced by the treatment and you are unaware of when the variable was measured, we recommend seeking clarification from others or from consulting documentation from the data source.


## How does including post-treatment variables lead to bias?

Post-treatment variables lead to bias by creating unfair comparisons. Comparisons become unfair because post-treatment variables have different [potential outcomes]() that depend on the treatment variable. To illustrate this, imagine a hypothetical study on if an exercise program causes increased strength. We'll use variable `z` to represent whether or not an individual participated in the exercise program and variable `y` to represent strength at the end of the program. One week, midway through the program, the number of times each individual went to the gym to exercise was recorded with the variable `gym`.

It is easy to imagine how each individual would have a different value of `gym` depending upon whether or not they were participating in the exercise program. All participants in the study different [potential outcomes]() for both `y` and `gym`. A table of all observed and potential outcomes for 3 participants from the exercise study would look like this:

| individual | z | gym | gym if z = 0 | gym if z = 1 | y | y  if z = 0 | y if z = 1 |
| :---: | :---:| :---: | :---: | :---: |:---: | :---: | :---: |:---: |
| Cong    |0|1|  1  |  3  |120|120|130|
| Andi    |1|3|  1  |**3**|130|120|130|
| Lindsey |0|3|**3**|  5  |135|135|140|

We can see that Cong and Andi would be a fair comparisons because they resemble each other across all potential outcomes for `y` and `gym`. Recall that we can never observe both potential outcomes and only have access to the observed value that is determined by the treatment(`z`). If we control for the **observed value** of `gym`, Cong and Andi no longer appear similar! Rather than making the fair comparison between Cong and Andi, a statistical model that controls for the **observed value** of `gym` would be making the unfair comparison between Andi and Lindsey, who have very different potential outcomes. This is not a problem for pre-treatment variables because it is impossible for them to depend upon the treatment. 

Suppose instead of controlling for the post-treatment variable `gym`, we had a pre-treatment variable `gym_pre` which measured the number of times each individual had gone to the gym the week before the exercise program began. Pre-treatment variables like `gym_pre` do not have different [potential outcomes]() that depend the treatment variable. Put another way, it is impossible for `gym_pre` to change depending on if an individual participated in the exercise program. 

| individual | z | gym_pre | y | y  if z = 0 | y if z = 1 |
| :---: | :---:| :---: | :---: | :---: |:---: | :---: | :---: |:---: |
| Cong    |0|0|120|120|130|
| Andi    |1|0|130|120|130|
| Lindsey |0|2|135|135|140|

Pre-treatment variables do not have [potetnial outcomes]() that depend on the treatment variable. When we adjust for the pre-treatment variable `gym_pre` our statistical model would be making the fair comparison between Cong and Andi rather than the unfair comparison between Cong and Lindsey that arose when we controlled for a post-treatment variable. 

If you ever need to formally explain why post-treatment variables are problematic you can use the following logic: 

- For a causal estimate to be unbiased both potential outcomes of outcome variable $y$ need to be   independent of the treatment variable $z$. In formal notation this is stated as: 

$$ y^0, y^1 \prep z $$

- Let $X$ represent pre-treatment variables. When we control for or condition on $X$ both potential outcomes of outcome variable $y$ remain independent of treatment variable $z$. In formal notation this is stated as:

$$ y^0, y^1 \prep z|X $$

- Let $Q$ represent post-treatment variables. When we control for or condition on $Q$, generally, both potential outcomes of outcome variable $y$ are not independent of treatment variable $z$. In formal notation this is stated as


$$ y^0, y^1 \not\!\prep z|X,Q$$


## Recap

Including post-treatment variables as predictors in a causal analysis should be avoided. As we saw in the bugs example, including post-treatment variables can distort causal analyses and lead you to incorrect conclusions. Post-treatment variables are any variables that occurred after the treatment was assigned and could possibly be influenced by the treatment. Statistical models with post-treatment variables make unfair comparisons and are biased because models do not have access to the potential outcomes of those variables. 

## Related modules
You can learn more about bias is [here]() 

You can learn more about simulation is [here]() 

You can learn more about potential outcomes [here]()

You can learn more about what makes a comparison fair or unfair [here]()

## Citations and Readings


